<?php
#######################################
# TPLManager - Version 1.2 (by awids) #
#######################################

define('BOX_CONFIGURATION_604', 'Text-Verwaltung');
define('TPL_CONF_PAGEINFO', '<strong>Auf dieser Seite k&ouml;nnen Sie verschiedene Text-Bausteine verwalten und Texte festlegen, die im Frontend angezeigt werden sollen.</strong><br><br>Die Text-Bausteine k&ouml;nnen f&uuml;r jede aktivierte/installierte Sprache definiert werden - auch nachtr&auml;glich, falls Sie sp&auml;ter noch weitere Sprachen hinzuf&uuml;gen.<br><br>&Uuml;ber den Content-Manager k&ouml;nnen Sie (mehrsprachig) den Content f&uuml;r Ank&uuml;ndigungen und Kundenhinweise im Kopfbereich Ihres Shops erstellen und hier der Box dann entsprechend zuweisen. Sie brauchen dann einfach nur den Kundenhinweis aktivieren, eine Klasse, den soeben erstellten Content sowie die Anzeige-Position (auf welchen Seiten) ausw&auml;hlen und schon wird Ihre Meldung (z. B. Urlaubsmeldung oder Hinweis auf versp&auml;tete Lieferzeiten) im Shop angezeigt.');
define('TPL_BOX_STANDARD_DESC', 'M&ouml;chten Sie die Box <strong>%s</strong> im Frontend anzeigen lassen?');
define('TPL_NAV_TEXT1_TITLE', 'Breadcrumb: TOP-Titel');
define('TPL_NAV_TEXT1_DESC', 'Geben Sie hier an, wie die 1. Position in der Breadcrumb (Standard: "Startseite") benannt werden soll. Viele tragen hier gerne ihren Shopnamen ein, damit eine Brutkrumenspur nach folgendem Schema entsteht: <i>Shopname > Kategorie 1 > Unterkategorie 2 > Produkt 3</i>');
define('TPL_NAV_TEXT2_TITLE', 'Breadcrumb: Katalog-Titel');
define('TPL_NAV_TEXT2_DESC', 'Wurde Ihr Shop in einem Unterverzeichnis installiert, erscheint im Standard ein weiterer Breadcrumb-Eintrag mit der Bezeichnung "Katalog" auf Position 2. Geben Sie hier an, wie diese Position benannt werden soll. Sofern Sie den Shop <u>nicht</u> in einem Unterverzeichnis installiert haben, k&ouml;nnen Sie diese Felder ignorieren.');
define('TPL_COPYRIGHT_TEXT_TITLE', 'Footer: Copyright');
define('TPL_COPYRIGHT_TEXT_DESC', 'Tragen Sie hier bitte ein, wer das allgemeine Copyright an Ihrer Seite hat. (Standard: <i>'.STORE_NAME.'</i>) Dies kann Ihr Name oder Ihre Firmenbezeichnung sein. Hier d&uuml;rfte f&uuml;r alle Sprachen dieselbe Angabe gelten. Die Sprachunterscheidung findet an dieser Stelle nur statt, falls Sie Zusatzinformationen wie z. B. "Alle Rechte vorbehalten" (o. &auml;.) angeben wollen.');
define('TPL_FRONTINFO_TEXT_TITLE', 'Kunden-Hinweis: Status');
define('TPL_FRONTINFO_TEXT_DESC', 'M&ouml;chten Sie den integrierten &raquo;Kunden-Hinweis&laquo; aktivieren? Beachten Sie bitte, dass es sich hierbei <u>nicht</u> um das Modul "Customers Notice" aus dem modified-Forum handelt, sondern eine eigene L&ouml;ung zum Einsatz kommt, weswegen Sie im entsprechenden Foren-Thread auch keinen Support erhalten k&ouml;nnen.');
define('TPL_FRONTINFO_CLASS_TITLE', 'Kunden-Hinweis: Klasse');
define('TPL_FRONTINFO_CLASS_DESC', 'Geben Sie an, in welcher CSS-Klasse Ihr Kunden-Hinweis erscheinen soll. "infomessage" hat einen hellgr&uuml;nen Hintergrund und dunkelgr&uuml;ne Schrift, "errormessage" hat einen hellroten Hintergrund und dunkelrote Schrift.');
define('TPL_FRONTINFO_CONTENT_TITLE', 'Kunden-Hinweis: Content');
define('TPL_FRONTINFO_CONTENT_DESC', 'Sofern in dieser Liste noch kein passender Eintrag zu finden ist, begeben Sie sich zum Content-Manager und legen einen entsprechenden Eintrag an. Das dort befindliche &Uuml;berschriften-Feld stellt die 1. Zeile in Ihrer Kunden-Mitteilung dar und wird gr&ouml;&szlig;er und in Fettschrift dargestellt. Vergessen Sie nicht, Ihren Content in der daf&uuml;r vorgesehenen Einstellung aktiv zu schalten, ansonsten wird Ihr Text nicht angezeigt. Die verschiedenen Sprachversionen pflegen Sie direkt im Content-Manager.'.((!empty(TPL_FRONTINFO_CONTENT)) ? '<a class="button" onclick="this.blur();" title="Content bearbeiten" style="text-decoration:none;float:right;" href="'.xtc_href_link(FILENAME_CONTENT_MANAGER, 'action=edit&coID='.TPL_FRONTINFO_CONTENT, 'NONSSL').'">Content bearbeiten</a>' : '').'<a class="button" onclick="this.blur();" title="Content anlegen" style="text-decoration:none;float:right;" href="'.xtc_href_link(FILENAME_CONTENT_MANAGER, 'action=new', 'NONSSL').'">Neuer Content</a>');
define('TPL_FRONTINFO_POS_TITLE', 'Kunden-Hinweis: Anzeige');
define('TPL_FRONTINFO_POS_DESC', 'Legen Sie fest, auf welchen Seiten der Kundenhinweis angezeigt werden soll. W&auml;hlen Sie hier zwischen <u>nur auf der Startseite</u> (startpage), <u>nur im Checkout</u> (only_on_checkout), <u>&uuml;berall, nur nicht im Checkout</u> (not_on_checkout) oder <u>auf allen Seiten</u> (alle).');
define('TPL_FOOTER_CONTACT_INFO_TITLE', 'Footer: Kontaktinformationen');
define('TPL_FOOTER_CONTACT_INFO_DESC', 'Tragen Sie hier Ihre Kontaktinformationen ein. Diese werden im Footer in der ersten Box angezeigt.');
?>